import { UserNote } from './types';

export interface BookContentItem {
  id: string;
  title: string;
  description: string;
  page: number;
}

export const BOOK_CONTENTS: Record<string, BookContentItem[]> = {
  sozler: [
    { id: 'sz-1', title: '1. Söz', description: 'Besmelenin esrarı', page: 5 },
    { id: 'sz-2', title: '2. Söz', description: 'İmanlı bakış açısının özellikleri (Gaybe iman neler kazandırıyor? Şehre giren iki adam)', page: 16 },
    { id: 'sz-3', title: '3. Söz', description: 'İbadetin insan hayatına etkisi (Farklı yollardan hedefe giden iki asker)', page: 18 },
    { id: 'sz-4', title: '4. Söz', description: 'Günde 5 vakit namazın kazandırdıkları ve önemi (24 altın sermaye alan iki hizmetkar)', page: 20 },
    { id: 'sz-5', title: '5. Söz', description: 'Namaz ve ibadetin asıl yaratılış vazifemiz olduğu (Askeriyede rızkını arayan asker bahsi)', page: 22 },
    { id: 'sz-6', title: '6. Söz', description: 'Varlığını ve imkanlarını Allah\'a kulluğa ve dinine hizmete ayırmanın önemi (Emanet çiftliği satmayan hizmetkar)', page: 25 },
    { id: 'sz-7', title: '7. Söz', description: 'İnanç ve ibadetin hayatımıza katkısı (Sürgün ve asılmak üzere olan yaralı adamın kıssası)', page: 30 },
    { id: 'sz-8', title: '8. Söz', description: 'İnsan ve yaşadığı dünya niçin yaratıldı? (Lokanta, çöl ve kuyu macerası)', page: 34 },
    { id: 'sz-9', title: '9. Söz', description: 'Namazın beş vakte tahsisinin hikmetleri', page: 40 },
    { id: 'sz-10', title: '10. Söz', description: 'Haşir Risalesi (Ahirete iman hakikatleri)', page: 48 },
    { id: 'sz-11', title: '11. Söz', description: 'Evrenin varoluş hikmeti ve insanın konumu (Sultanın saray gezisi daveti kıssası)', page: 120 },
    { id: 'sz-12', title: '12. Söz', description: 'Felsefe ile Kur\'an ve İslam\'ın hayatı yorumlama biçiminin kıyaslanması', page: 130 },
    { id: 'sz-13', title: '13. Söz', description: 'İmani metinlerle felsefi metinlerin kıyaslanması (Meyve Risalesinden parçalar ve Hüve Nüktesi)', page: 137 },
    { id: 'sz-14', title: '14. Söz', description: 'Altı günde yaratılış, kader, meleklerin tesbihi, vahidiyet-ehadiyet hakikati ve zelzele bahsi', page: 163 },
    { id: 'sz-15', description: 'Semavat, melek ve ruhani ilişkisi ve Kur\'an hakikatleri', title: '15. Söz', page: 176 },
    { id: 'sz-16', description: 'Tecelli, yansıma, Allah\'ın kudreti ve yakınlığı', title: '16. Söz', page: 193 },
    { id: 'sz-17', description: 'Teodise problemi (Hayır-şer tartışması ve kader)', title: '17. Söz', page: 202 },
    { id: 'sz-18', description: 'Teodise ve tecelli gibi zat-ı uluhiyet ile ilgili sırlar', title: '18. Söz', page: 230 },
    { id: 'sz-19', description: 'Risalet-i Ahmediyenin akıl açısından temellendirilmesi (14 Reşha)', title: '19. Söz', page: 235 },
    { id: 'sz-20', description: 'Kur\'an ayetlerine yapılan bir itiraza cevap ve Kur\'an ve modern bilim', title: '20. Söz', page: 245 },
    { id: 'sz-21', description: 'Beş vakit namazın hikmeti ve nefsin tembelliğine beş ikaz - Vesvese Bahsi', title: '21. Söz', page: 269 },
    { id: 'sz-22', description: '12 Bürhan ve 12 Lem\'a ile kâinatın Allah\'ın varlığını ispat etmesi', title: '22. Söz', page: 279 },
    { id: 'sz-23', description: 'İnsana kazandırdıkları açısından iman ve imanın insan mahiyetindeki yeri', title: '23. Söz', page: 311 },
    { id: 'sz-24', description: 'Esma-i Hüsna ve sıfat bahsi, Katre-Şule-Zühre, kıyamet alametlerinin tahlili', title: '24. Söz', page: 332 },
    { id: 'sz-25', description: 'Mucizat-ı Kuraniyye Risalesi (Kur\'an\'ın belagati, i\'cazı ve muvazenesi)', title: '25. Söz', page: 365 },
    { id: 'sz-26', description: 'Kader Risalesi (Kader ve cüz-i ihtiyarînin telifi)', title: '26. Söz', page: 463 },
    { id: 'sz-27', description: 'İçtihad Risalesi ve sahabe derecelerinin sırları', title: '27. Söz', page: 480 },
    { id: 'sz-28', description: 'Cennete dair tefsiri hakikatler', title: '28. Söz', page: 497 },
    { id: 'sz-29', description: 'Beka-i ruh, melaike, haşir ve kıyamet delilleri', title: '29. Söz', page: 504 },
    { id: 'sz-30', description: 'Ene (Ego/Benlik) sırrı ve tahavvülat-ı zerrat (Atomların hareketlerindeki hikmet)', title: '30. Söz', page: 535 },
    { id: 'sz-31', description: 'Miraç Risalesi (Peygamber Efendimizin mucizevi miracı)', title: '31. Söz', page: 559 },
    { id: 'sz-32', description: 'Tevhid, zat, sıfat, şuunat, esma ve ilahi muhabbet bahsi', title: '32. Söz', page: 590 },
    { id: 'sz-33', description: 'Afakta ve enfüste Allah\'ın varlığını gösteren 33 pencereli tevhid risalesi', title: '33. Söz', page: 653 }
  ],
  mektubat: [
    { id: 'mk-1', title: '1. Mektup', description: 'Dört tabaka-i hayat, ölümün nimeti, cehennemin yeri, mecazi ve hakiki aşk', page: 5 },
    { id: 'mk-2', title: '2. Mektup', description: 'Bediüzzaman Said Nursi\'nin kimseden hediye kabul etmeme düsturu ve sebepleri', page: 13 },
    { id: 'mk-3', title: '3. Mektup', description: 'Kâinattaki tefekkür dersleri ve marifetullah nurları', page: 15 },
    { id: 'mk-4', title: '4. Mektup', description: 'Yıldızname tefekkürü ve kâinattaki nizam', page: 19 },
    { id: 'mk-5', title: '5. Mektup', description: 'İman hakikatlerinin tasavvufi yollar içindeki yüce yeri', page: 22 },
    { id: 'mk-6', title: '6. Mektup', description: 'Gurbet tefekkürü ve manevi teselli mertebeleri', page: 24 },
    { id: 'mk-7', title: '7. Mektup', description: 'Peygamber Efendimiz (sav)\'in Hz. Zeynep ile evliliğine dair suallere cevaplar', page: 27 },
    { id: 'mk-8', title: '8. Mektup', description: 'Rahmaniyet ve Rahimiyet ilahi sıfatlarının nurları', page: 30 },
    { id: 'mk-9', title: '9. Mektup', description: 'Kerametin izharı ve iman ile İslam kavramlarının derin farkları', page: 32 },
    { id: 'mk-10', title: '10. Mektup', description: 'İmam-ı Mübin ve Kitab-ı Mübin hakikati, meydan-ı haşir', page: 36 },
    { id: 'mk-11', title: '11. Mektup', description: 'Vesvese ve miras ayetindeki hikmetler', page: 39 },
    { id: 'mk-12', title: '12. Mektup', description: 'Hz. Adem\'in cennetten ihracı, şeytanın yaratılış hikmeti ve musibetlerin sırrı', page: 42 },
    { id: 'mk-13', title: '13. Mektup', description: 'Üstadın rızık ve geçim tarzına dair kişisel soruların şeffaf cevapları', page: 46 },
    { id: 'mk-14', title: '14. Mektup', description: 'Muhtelif tefekkür soruları ve cevaplar', page: 50 },
    { id: 'mk-15', title: '15. Mektup', description: 'Cemel ve Sıffin vakaları, sahabe ihtilafları, Mehdi ve Deccal hakikatleri', page: 50 },
    { id: 'mk-16', title: '16. Mektup', description: 'Siyasetten çekilmenin hikmetleri ve hizmet prensipleri', page: 61 },
    { id: 'mk-17', title: '17. Mektup', description: 'Çocuk Taziyenamesi (Vefat eden sabilerin ahiretteki durumları)', page: 77 },
    { id: 'mk-18', title: '18. Mektup', description: 'Fütuhat-ı Mekkiye ifadeleri, vahdet-i vücud felsefesinin tahlili', page: 81 },
    { id: 'mk-19', title: '19. Mektup', description: 'Mucizat-ı Ahmediye Risalesi (Peygamber Efendimizin bereket, şifa, ihbarat-ı gaybiye mucizeleri)', page: 88 },
    { id: 'mk-20', title: '20. Mektup', description: 'Tevhid kelimesinin 11 kelimesindeki marifet ve iman nurları', page: 222 },
    { id: 'mk-21', title: '21. Mektup', description: 'Ana-baba hakkı ve rızalarını kazanmanın önemi', page: 259 },
    { id: 'mk-22', title: '22. Mektup', description: 'Uhuvvet Risalesi (Müslümanlar arası muhabbet ve ittifak düsturları)', page: 262 },
    { id: 'mk-23', title: '23. Mektup', description: 'Müminin mümine duası, sahabe dışındakilere unvanlar, müçtehit ve aktab farkı', page: 278 },
    { id: 'mk-24', title: '24. Mektup', description: 'Teodise, Esma ve sıfatların cilveleri, duanın mahiyeti', page: 284 },
    { id: 'mk-25', title: '25. Mektup', description: 'Kur\'an ayetlerinin i\'cazına dair açıklamalar', page: 308 },
    { id: 'mk-26', title: '26. Mektup', description: 'Kuran\'a bitarafane bakış hatası, ırkçılık tehlikesi ve muhtelif meseleler', page: 309 },
    { id: 'mk-27', title: '27. Mektup', description: 'Barla, Kastamonu ve Emirdağ Lahikaları mektupları', page: 346 },
    { id: 'mk-28', title: '28. Mektup', description: 'Hizmet-i imaniyeye ait kerametler, rüya tabirleri ve Şükür Risalesi', page: 346 },
    { id: 'mk-29', title: '29. Mektup', description: 'Ramazan Risalesi, Hücümat-ı Sitte (Nefsin altı tuzağı) ve Tasavvuf dersleri', page: 388 },
    { id: 'mk-30', title: '30. Mektup', description: 'İşarat-ül İ\'caz tefsirinin takdimi', page: 461 },
    { id: 'mk-31', title: '31. Mektup', description: 'Lem\'alar Risalesinin telif planı ve bölümleri', page: 461 },
    { id: 'mk-32', title: '32. Mektup', description: 'Lemeat (Manzum risale ve hakikatler)', page: 461 },
    { id: 'mk-33', title: '33. Mektup', description: '33 Pencereli Otuz Üçüncü Söz tevhid dersleri', page: 461 }
  ],
  lemalar: [
    { id: 'lm-1', title: '1. Lem\'a', description: 'Hz. Yunus (as)\'ın münacatı ve tevbenin her kula mühim dersi', page: 5 },
    { id: 'lm-2', title: '2. Lem\'a', description: 'Hz. Eyyub (as)\'ın sabır kıssası ve manevi hastalıklarımıza şifası', page: 8 },
    { id: 'lm-3', title: '3. Lem\'a', description: 'Beka zikri ("Ya Baki Entel Baki") ve fani hayatın ebedileşmesi sırrı', page: 14 },
    { id: 'lm-4', title: '4. Lem\'a', description: 'Minhac-üs Sünne (Ehl-i Beyt muhabbetinin ve sünnet-i seniyyenin önemi)', page: 19 },
    { id: 'lm-5', title: '5. Lem\'a', description: 'Hasbi Risalesine mukaddime ve tefekkür dersleri', page: 27 },
    { id: 'lm-6', title: '6. Lem\'a', description: '"La Havle Vela Kuvvete İlla Billah" zikrinin esrarı', page: 27 },
    { id: 'lm-7', description: 'Fetih Suresi son ayetlerinin gaybi müjdeleri ve Kuran\'ın ihbaratı', title: '7. Lem\'a', page: 28 },
    { id: 'lm-8', description: 'Keramet-i Gavsiye (Abdülkadir Geylani hazretlerinin işarat-ı gaybiyesi)', title: '8. Lem\'a', page: 39 },
    { id: 'lm-9', description: 'Manevi tefekkür dersleri ve esrarlı nükte', title: '9. Lem\'a', page: 39 },
    { id: 'lm-10', description: 'Şefkat Tokatları (Hizmetteki kusurların şefkatli ikazları)', title: '10. Lem\'a', page: 40 },
    { id: 'lm-11', description: 'Mirkat-üs Sünne (Sünnet-i Seniyyeye ittibanın lüzumu ve hikmetleri)', title: '11. Lem\'a', page: 49 },
    { id: 'lm-12', description: 'Açlıktan ölenlerin rızık hakikati, göklerin yedi tabaka olması meselesi', title: '12. Lem\'a', page: 62 },
    { id: 'lm-13', description: 'Şeytanın hile ve vesveselerinden Allah\'a sığınmanın (İstiaze) mühim hikmetleri', title: '13. Lem\'a', page: 70 },
    { id: 'lm-14', description: 'Dünyanın öküz ve balık üstünde olması, Al-i Aba sırlar, Besmele tefekkürü', title: '14. Lem\'a', page: 90 },
    { id: 'lm-15', description: 'Risale-i Nur Külliyatı fihristesinin ehemmiyeti', title: '15. Lem\'a', page: 103 },
    { id: 'lm-16', description: 'Sedd-i Zülkarneyn, Ye\'cüc-Me\'cüc, Deccal ve Hz. İsa\'nın nüzulü bahisleri', title: '16. Lem\'a', page: 103 },
    { id: 'lm-17', description: 'Notalar halinde kaleme alınmış muhtelif tefekkür uyanışları', title: '17. Lem\'a', page: 113 },
    { id: 'lm-18', description: 'Celcelutiye kasidesinde geçen risalelere işaretler ve gaybi müjdeler', title: '18. Lem\'a', page: 138 },
    { id: 'lm-19', description: 'İktisat Risalesi (Bereket, kanaat ve iktisadın mühim düsturları)', title: '19. Lem\'a', page: 139 },
    { id: 'lm-20', description: 'İhlas Risalesi (Hizmette ihlası kazanmanın ve muhafaza etmenin yolları)', title: '20. Lem\'a', page: 148 },
    { id: 'lm-21', description: 'İhlas hakkında ikinci mühim risale ve düsturlar', title: '21. Lem\'a', page: 159 },
    { id: 'lm-22', description: 'Said Nursi\'nin mahkemelerdeki iman ve Kuran müdafaaları', title: '22. Lem\'a', page: 168 },
    { id: 'lm-23', description: 'Tabiat Risalesi (Tabiatçılık fikrini kökten çürüten aklî bürhanlar)', title: '23. Lem\'a', page: 176 },
    { id: 'lm-24', description: 'Tesettür Risalesi (Kadının fıtri tesettür ihtiyacı ve toplumsal hikmetleri)', title: '24. Lem\'a', page: 195 },
    { id: 'lm-25', description: 'Hastalar Risalesi (Hastalıkların günahlara kefaret olması, 25 Deva)', title: '25. Lem\'a', page: 205 },
    { id: 'lm-26', description: 'İhtiyarlar Risalesi (Yaşlılığın getirdiği manevi nurlar, 26 Rica)', title: '26. Lem\'a', page: 222 },
    { id: 'lm-27', description: 'Eskişehir Müdafaası hakikatleri', title: '27. Lem\'a', page: 267 },
    { id: 'lm-28', description: 'Muhtelif dini ve vatani sorulara verilen hikmetli cevaplar', title: '28. Lem\'a', page: 268 },
    { id: 'lm-29', description: 'Arapça tefekkür ve marifet ufku', title: '29. Lem\'a', page: 284 },
    { id: 'lm-30', description: 'İsm-i Azam Risalesi (Kuddüs, Adl, Hakem, Ferd, Hayy, Kayyum tefsiri)', title: '30. Lem\'a', page: 304 },
    { id: 'lm-31', description: 'Şualar Külliyatına işaretler', title: '31. Lem\'a', page: 357 },
    { id: 'lm-32', description: 'Lemeat hakikatlerinin telif planı', title: '32. Lem\'a', page: 357 },
    { id: 'lm-33', description: 'Muhtelif zeyiller ve fihristler', title: '33. Lem\'a', page: 357 }
  ],
  sualar: [
    { id: 'sh-1', title: '1. Şua', description: 'Risale-i Nur hizmetine işaret eden Kur\'an ayetlerinin tefsirleri', page: 685 },
    { id: 'sh-2', title: '2. Şua', description: 'Tevhid ve vahdaniyet dersleri (Üç mühim makamda esma tecellileri)', page: 5 },
    { id: 'sh-3', title: '3. Şua', description: 'Münacat Risalesi (Bütün mahlukatın lisanıyla yapılan muhteşem dua)', page: 42 },
    { id: 'sh-4', title: '4. Şua', description: 'Hasbi Risalesi ("Hasbünallahu ve ni\'mel vekil" sırrı)', page: 60 },
    { id: 'sh-5', title: '5. Şua', description: 'Ahir zaman, Deccal, Süfyan ve kıyamet hadislerinin tefsirli yorumları', page: 578 },
    { id: 'sh-6', title: '6. Şua', description: 'Tehiyyat duasının namazdaki ehemmiyeti ve marifet dersi', page: 92 },
    { id: 'sh-7', title: '7. Şua', description: 'Âyet-ül Kübra Risalesi (Kâinattan yaratıcısını soran bir seyyahın müşahedeleri)', page: 98 },
    { id: 'sh-8', title: '8. Şua', description: 'Hz. Ali (ra)\'ın Celcelutiye kasidesindeki Risale-i Nur\'a gaybi işaretleri', page: 727 },
    { id: 'sh-9', title: '9. Şua', description: 'Haşir ve ahirete inanmanın insan şahsi ve içtimai hayatına kazandırdıkları', page: 180 },
    { id: 'sh-10', title: '10. Şua', description: 'Şualar Risalesi fihristesi ve tefekkür dersleri', page: 191 },
    { id: 'sh-11', title: '11. Şua', description: 'Meyve Risalesi (Denizli hapishanesinde telif edilen, iman dersleri barındıran 11 mesele)', page: 192 },
    { id: 'sh-12', title: '12. Şua', description: 'Bediüzzaman\'ın Denizli Mahkemesi müdafaası', page: 278 },
    { id: 'sh-13', title: '13. Şua', description: 'Afyon Mahkemesi müdafaaları ve hapishane mektupları', page: 293 },
    { id: 'sh-14', title: '14. Şua', description: 'Afyon Mahkemesi geniş müdafaaları ve talebelerinin mektupları', page: 347 },
    { id: 'sh-15', title: '15. Şua', description: 'El-Hüccet-üz Zehra Risalesi (Tevhid, kelime-i şehadet ve iman rüknü tefsiri)', page: 597 }
  ]
};
